### ISSUE TITLE
Velocity does not ping correctly

### ISSUE THREAD

**Issue by nicolasvac** [alteamc/minequery#6]
Hello, i run a velocity 3.1 server.

When i try to use the example in the README, i get:

panic: ping error: response error: expected packet 0x0 but got 0x1 instead

**Comment by dreamscached** [comment]
It seems that the error is caused by Velocity server actually responding to ping packet sent, unlike Notchian servers used for testing.

**Comment by dreamscached** [comment]
Closing as fixed.
